
portLocal = 9996
port = 9997
serviceId = "pdst001"

[db]
    host      = "deploy-db-1"
	hostLocal = "localhost"
	port      = 5432
	user      = "postgres"
	password  = "1234"
	dbname    = "test_app"

[kafka]
  serverAddress = "127.0.0.1"
  serverPort = 9092
